### ISSUE TITLE
Importing problem using macOS 

### ISSUE THREAD

**Issue by CamTHz** [dotTHzTAG/CambridgeTHzConverter#2]
When trying to import two CSV files (Menlo raw data) into CaTx I run into the following error message when I press 'Deploy Data':

> Unrecognized method, property, or field 'DEBUGMsgLabel' for class 'CaTx'.
> 
> Error in CaTx/ClearMemoryButtonPushed (line 474)
>                 app.DEBUGMsgLabel.Text = '';
> 
> Error in appdesigner.internal.service.AppManagementService/executeCallback (line 172)
>                 callback(appOrUserComponent, event);
> 
> Error in matlab.apps.AppBase>@(source,event)executeCallback(ams,app,callback,requiresEventData,event) (line 62)
>             newCallback = @(source, event)executeCallback(ams, ...
>  
> Error using appdesservices.internal.interfaces.model.AbstractModel/executeUserCallback
> Error while evaluating Button PrivateButtonPushedFcn.

The data refuses to deploy.

**Comment by jl2112tag** [comment]
Thank you for the report, It was due to unintentionally deleted debug message label and it's fixed.  Cheers!

**Comment by CamTHz** [comment]
Thanks, works perfectly now!
