### ISSUE TITLE
Engines for Terapulse 4000 reflection mode

### ISSUE THREAD

**Issue by Chi-Ki-Leung** [dotTHzTAG/CambridgeTHzConverter#5]
1. TeraPulse4000_RX_BaselineIncluded_UCAM: Using this engine, after the deploy button is pressed, the app enters the loading mode infinitely and no data can be imported

2. TeraPulse4000_RX_Focus_UCAM: The baseline and reference time and amplitude data cannot be extracted, but only the sample time and amplitude.

3. If the sample measurement is not taken immediately after the reference and baseline measurement, the engine cannot perform data extraction.

I would very much appreciate if theses engine can be updated so that all baseline, reference and sample time and amplitude data can be successfully imported. Thank you very much!

**Comment by jl2112tag** [comment]
Hi Chi Ki,

Thank you for the comment. I want to let you know that recently updated CaTx no longer uses MATLAB *.m file based engines to import the measurement data. Instead, CaTx now directly import datasets using programmable/editable deployment recipes. The inquiries above can be implemented by creating a new recipe in the tab entitled 'Deployment Recipes'. Please try.

Cheers,
Jongmin
