### ISSUE TITLE
Failed to read Configuration.json when open the CaTx after installed first time

### ISSUE THREAD

**Issue by MinYoung96** [dotTHzTAG/CambridgeTHzConverter#7]
Hello, thank you very much for your contribution. This is a great project! However, there was a problem when I opened it for the first time. The software prompted me to "Failed to read Configuration.json". How can I solve this problem?
![Snipaste_2024-11-06_21-12-29](https://github.com/user-attachments/assets/40a7caf7-4196-48d1-9263-732d558fcf35)
![Snipaste_2024-11-06_21-13-02](https://github.com/user-attachments/assets/fb472fca-b0a2-471d-ab01-13cd7e3ffe90)

**Comment by jl2112tag** [comment]
Hi MinYoung,

Thank you for your comment and your participation in the project. It seems the JSON file loading issue has been sorted out. If so, would it be possible to let us know what the resolution was? This information would be helpful for documentation purposes and for other uses who might encounter similar issues in the future. Thank you again!

Jongmin

**Comment by MinYoung96** [comment]
Jongmin


Thank you for your attention to the issue. The problem of the failed reading of the JSON file before was mainly due to the failure to install strictly in accordance with the guidelines. This problem can be solved as long as the guidelines are strictly followed.


MinYoung


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Feeling??
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dotTHzTAG/CaTx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月11日(星期一) 上午8:49
***@***.***&gt;;
抄送:&nbsp;"              ***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [dotTHzTAG/CaTx] Failed to read Configuration.json when open the CaTx after installed first time (Issue #7)





 
Hi MinYoung,
 
Thank you for your comment and your participation in the project. It seems the JSON file loading issue has been sorted out. If so, would it be possible to let us know what the resolution was? This information would be helpful for documentation purposes and for other uses who might encounter similar issues in the future. Thank you again!
 
Jongmin
